import type { DrawingItem } from '../types/drawing';

export const MOCK_DRAWINGS: DrawingItem[] = [
  {
    id: 1,
    title: '1층 중앙 출입구 주변 배치도',
    description: '주말 운영 시 출입구 혼잡이 예상되는 구역의 배치안입니다.',
    createdBy: '김하늘',
    createdAt: '2026-08-05T10:24:00',
    status: '작성 중',
  },
  {
    id: 2,
    title: '3층 팝업존 배치도',
    description: '팝업 매장 4개와 휴게 공간을 포함한 배치안입니다.',
    createdBy: '박지안',
    createdAt: '2026-08-04T16:40:00',
    status: '검토 대기',
  },
  {
    id: 3,
    title: '지하 1층 푸드코트 행사 배치도',
    description: '푸드코트 확장 행사 구역의 배치안입니다.',
    createdBy: '이도현',
    createdAt: '2026-08-03T09:15:00',
    status: '검토 중',
  },
  {
    id: 4,
    title: '2층 전시존 배치도',
    description: '브랜드 전시 부스 배치와 관람 동선을 정리한 배치안입니다.',
    createdBy: '김하늘',
    createdAt: '2026-08-01T14:02:00',
    status: '검토 완료',
  },
  {
    id: 5,
    title: '5층 이벤트홀 배치도',
    description: '대규모 행사용 무대와 좌석 배치안입니다.',
    createdBy: '최서윤',
    createdAt: '2026-07-29T11:30:00',
    status: '위험 발견',
  },
  {
    id: 6,
    title: '로비 팝업스토어 배치도',
    description: '로비 중앙 팝업스토어 운영 배치안입니다.',
    createdBy: '정민준',
    createdAt: '2026-07-28T17:45:00',
    status: '검토 중',
  },
  {
    id: 7,
    title: '옥상 정원 행사 배치도',
    description: '야외 행사 구역과 비상구 동선을 포함한 배치안입니다.',
    createdBy: '이도현',
    createdAt: '2026-07-25T10:00:00',
    status: '검토 완료',
  },
  {
    id: 8,
    title: '지하 2층 주차장 행사 배치도',
    description: '주차장 내 행사 부스 배치안입니다.',
    createdBy: '최서윤',
    createdAt: '2026-07-22T13:20:00',
    status: '작성 중',
  },
];
